name: Building docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docs and push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Install and Run Typedoc
        run: npm install -g typedoc && npx typedoc
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO:  git@github.com:Kikku-Discord-Bot/Kikku-Discord-Bot.github.io.git # The repository to push to
          BRANCH: main # The branch to push to
          FOLDER: docs # The folder to push
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          
